### ISSUE TITLE
Can't update item images

### ISSUE THREAD

**Issue by Razzmatazzz** [the-hideout/tarkov-data-manager#14]
Trying to fix the images for some items (the Killa helmet and faceshield) and I'm getting an s3 "Access Denied" error. The relevant code is [here](https://github.com/the-hideout/tarkov-data-manager/blob/9cf899567b92ed33f95b4a4dd614a16a2c1243f9/src/tarkov-data-manager/index.js#L477-L492).

Is the Bucket being set incorrectly? From the crons, I seem to recall it might not be an env variable anymore and is hard coded to `hideout-api`, is that right?

**Comment by austinhodak** [comment]
We had to change to a new bucket due to the domain switch, I'm guessing this got missed when we were changing things.

**Comment by Razzmatazzz** [comment]
If the bucket is being set via an env var, then it should be updated in the update-existing-bases job of the data manager. If the bucket is hard-coded, then it should be hard-coded everywhere or switched to an env var everywhere. Not sure which is preferable.

**Comment by Razzmatazzz** [comment]
Fixed by @GrantBirki!
